name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [main]
    types: [completed]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { name: petclinic-jar }
      - uses: webfactory/ssh-agent@v0.8.1
        with: { ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }} }
      - run: scp -o StrictHostKeyChecking=no target/*.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/
      - run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "nohup java -jar /home/ubuntu/*.jar > /dev/null 2>&1 &"
