name: Java CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # CI PHASE - BUILD AND TEST
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

  name: Java CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # CI PHASE - BUILD AND TEST
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: |
          chmod +x mvnw
          ./mvnw clean verify

      - name: SonarQube Scan
        if: github.ref == 'refs/heads/main' && secrets.SONAR_TOKEN != ''
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./mvnw sonar:sonar \
            -Dsonar.projectKey=Spring-PetClinic \
            -Dsonar.projectName='Spring-PetClinic' \
            -Dsonar.java.binaries=target/classes

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: petclinic-jar
          path: target/spring-petclinic-*.jar

  # CD PHASE - DEPLOYMENT
  deploy-to-ec2:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: petclinic-jar
          path: target/

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          scp -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no target/*.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/
          ssh -i ~/.ssh/ec2_key ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          pkill -f "java -jar spring-petclinic" || true
          nohup java -jar /home/ubuntu/spring-petclinic-*.jar > /home/ubuntu/app.log 2>&1 &
          EOF
